# Generated by Django 2.1.1 on 2018-12-19 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [['can_view_goldpage', 'Can view goldpage']]},
        ),
    ]
